server:
  port: 7001

eureka:
  instance:
#    hostname: eureka #eureka服务端实例名称 单机版
    hostname: eureka7001 #eureka服务端实例名称
  client:
    #表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版
#      defaultZone: http://eureka7002:7002/eureka/